### ISSUE TITLE
Couldn't run yo sourcejs, failed with error

### ISSUE THREAD

**Issue by unional** [sourcejs/generator-sourcejs#5]
I tried to run it with sudo.  But it still fail:
> fsevents@0.3.8 install /Users/hwong/codes/sourcejs2/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v3.0.0/node-v3.0.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hwong/codes/sourcejs2/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'

> contextify@0.1.14 install /Users/hwong/codes/sourcejs2/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v3.0.0/node-v3.0.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:992:10)
stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hwong/codes/sourcejs2/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.8

> phantomjs@1.9.7-15 install /Users/hwong/codes/sourcejs2/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip
Saving to /tmp/phantomjs/phantomjs-1.9.7-macosx.zip
Receiving...
\ [==============================----------] 76% 0.0s-
Received 9186K total.
Extracting zip contents
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.7-macosx.zip-extract-1439453877743/phantomjs-1.9.7-macosx -> /Users/hwong/codes/sourcejs2/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/hwong/codes/sourcejs2/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hwong/codes/sourcejs2/npm-debug.log

**Comment by unional** [comment]
last content was error when I try to run it with io.js.  Running it on OSX with node v0.12.7 works.

**Comment by operatino** [comment]
Hi, thanks for the report, I will re-check iojs compatibility. But anyway, since in 0.6 we will remove JSDom dependency (which is failing way to often, same as here), this issue will be fixed.
